name: Test CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:   
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        sdk: 
          - dev
          - beta
          - stable
          - 2.18.0-271.0.dev
          - 2.18.0-271.2.beta
          - 2.18.0-271.4.beta
        os:
          - macos-10.15
          - macos-11
          - macos-12
    steps:
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: ${{ matrix.sdk }}
      - name: create main.dart
        run: echo "void main() { print('Hello World!'); }" >> main.dart      
      - name : compile main.dart
        run : dart compile exe main.dart -o main
      - name : run main.dart
        run : ./main
