name: Test CI

defaults:
  env:
    MY_VAR: "a value a day keeps the empty variables at bay"

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
    branches: [ $default-branch ]    

jobs:   
  test:
    env:
      MY_OTHER_VAR: "another var, another chance"
    runs-on: ubuntu-latest
    steps:
      - name: Print var
        run: echo "${MY_VAR}"
      - name: Print other var
        run: echo "${MY_OTHER_VAR}"
