name: Test CI
  
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:   
  test:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      - run: echo "$PWD/depot_tools" >> $GITHUB_PATH
      - run: mkdir dart-sdk
      - run: cd dart-sdk && fetch --no-history dart
      - run: ./dart-sdk/sdk/buildtools/linux-x64/clang/bin/clang --version
