name: Test CI
  
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]    
env:
  MY_VAR: "a value a day keeps the empty variables at bay"

jobs:   
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print var
        run: echo "${MY_VAR}"
