name: Test CI
  
on:
  push:
    branches: [ main, always-fail ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]    
env:
  MY_VAR: "a value a day keeps the empty variables at bay"

jobs:   
  test:
    runs-on: ubuntu-latest
    steps:
      - name: lookup
        run: nslookup http://www.microsoft.com
      - name: lookup
        run: nslookup http://pub.invalid
        if: always()
      - name: Fail
        run: exit 1
