name: Test CI
  
on:
  push:
    branches: [ main, always-fail ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]    
env:
  MY_VAR: "a value a day keeps the empty variables at bay"

jobs:   
  test:
    runs-on: ubuntu-latest
    steps:
      - name: lookup www.microsoft.com
        run: nslookup www.microsoft.com
      - name: lookup example.com
        run: nslookup example.com
        if: always()
      - name: lookup invalid-url.foo
        run: nslookup invalid-url.foo
        if: always()
      - name: lookup pub.invalid
        run: nslookup pub.invalid
        if: always()
      - name: Fail
        run: exit 1
