name: Test CI
  
on:
  push:
    branches: [ main, always-fail ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]    
env:
  MY_VAR: "a value a day keeps the empty variables at bay"

jobs:   
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        run: exit 1
      - name: Print var
        if: always() && runner.os != 'sugar'
        run: echo "${MY_VAR}"
